spring.application.name=farmos
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/farmos
spring.datasource.username=postgres
spring.datasource.password=root@123

# This auto-creates tables for you
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port your server runs on
server.port=8081